name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Trigger this pipeline on pushes to the 'main' branch
  pull_request:
    branches:
      - master  # Trigger this pipeline on pull requests to the 'main' branch

jobs:
  # CI Job: Build and Test
  build_and_test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner
    steps:
      - name: Check out code
        uses: actions/checkout@v3  # Check out your repository

      - name: Set up JDK 21  # Configure Java; adjust version based on your project
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'  # Use Eclipse Temurin distribution of Java

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and Test with Maven
        run: mvn clean verify  # Verify phase will build the project and run tests

  # Optional CD Job: Deploy
  deploy:
    runs-on: ubuntu-latest
    needs: build_and_test  # Run this job only if build_and_test succeeds
    steps:
      - name: Check out code
        uses: actions/checkout@v3  # Check out your repository

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Deploy Application
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        run: |
          mvn clean deploy -DskipTests  # Deploy using Maven (e.g., to Nexus or Artifactory)
          echo "Deployment completed successfully!"
